[project]
name = "real-time-e-commerce-conversion-funnel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.14",
    "dbt-risingwave>=1.10.0",
    "kafka-python>=2.3.0",
]
